---

- name: Install communication tools
  hosts: dev
  become: yes
  tasks:
    - name: Download Teams deb
      ansible.builtin.get_url:
        url: https://go.microsoft.com/fwlink/p/?LinkID=2112886&clcid=0x40c&culture=fr-fr&country=FR
        dest: "/home/{{ ansible_user_id }}/Téléchargements/teams.deb"
      tags: teams

    - name: Install Teams
      ansible.builtin.apt:
        deb: "/home/{{ ansible_user_id }}/Téléchargements/teams.deb"
      tags: teams

    - name: Add Signal signing key
      ansible.builtin.get_url:
        url: https://updates.signal.org/desktop/apt/keys.asc
        dest: /etc/apt/keyrings/signal-desktop.asc
        mode: '0644'
      tags: signal

    - name: Add Signal repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/signal-desktop.asc] https://updates.signal.org/desktop/apt xenial main
        filename: signal
        state: present
      tags: signal

    - name: Install Signal
      ansible.builtin.apt:
        pkg:
          - signal-desktop
      tags: signal

    - name: Add Slack signing key
      ansible.builtin.get_url:
        url: https://packagecloud.io/slacktechnologies/slack/gpgkey
        dest: /etc/apt/keyrings/slack.asc
        mode: '0644'
      tags: slack

    - name: Add Slack repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/slack.asc] https://packagecloud.io/slacktechnologies/slack/debian/ jessie main
        filename: slack
        state: present
      tags: slack

    - name: Install Slack
      ansible.builtin.apt:
        pkg:
          - slack-desktop
      tags: slack
