---
# add discord (on debian bullseye, use the .tgz instead of the .deb
- hosts: dev
  tasks:
    - name: Download teams deb
      get_url:
        url: https://go.microsoft.com/fwlink/p/?LinkID=2112886&clcid=0x40c&culture=fr-fr&country=FR
        dest: "/home/{{ ansible_user_id }}/Téléchargements/teams.deb"
    - name: Install teams
      apt:
        deb: "/home/{{ ansible_user_id }}/Téléchargements/teams.deb"
  become: yes
    
