---

- name: "Install docker"
  hosts: dev
  roles:
    - role: geerlingguy.docker
      vars:
        # for fix debian testing bullseye
        docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
        docker_install_compose: true
        docker_compose_version: "1.28.2"
        docker_users:
          - "{{ ansible_user_id }}"
      become: yes
