---

- hosts: dev
  tasks:
    - name: Add Spotify apt key.
      shell: >
        curl -sSL https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg | apt-key add -
      args:
        warn: false
      become: yes

    - name: Add Spotify repository.
      apt_repository:
        repo: "deb http://repository.spotify.com stable non-free"
        state: present
        update_cache: true
      become: yes

    - name: "Install Spotify"
      apt:
        pkg:
          - spotify-client
      become: yes