---

- name: Install Spotify
  hosts: dev
  become: yes
  tasks:
    - name: Add Spotify signing key
      ansible.builtin.apt_key:
        url: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
        state: present
      tags: spotify

    - name: Add Spotify repository
      ansible.builtin.apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        filename: spotify
        state: present
      tags: spotify

    - name: Install Spotify
      ansible.builtin.apt:
        pkg:
          - spotify-client
      tags: spotify