---

- name: Install language Golang
  hosts: dev
  roles:
    - role: golang
  become: yes

- name: Install hugo extended
  hosts: dev
  roles:
    - role: hugo
      hugo_app: hugo_extended
      hugo_bin_path: /usr/local/bin
  become: yes
