---

- name: Install Mise
  hosts: dev
  tasks:
    - name: Install curl
      ansible.builtin.package:
        name: curl
        state: present
      become: yes

    - name: Download and install Mise
      ansible.builtin.shell: curl https://mise.run | sh
      args:
        creates: ~/.local/bin/mise

    - name: Add Mise to Zsh init
      ansible.builtin.lineinfile:
        path: ~/.zshrc.local
        line: 'eval "$(~/.local/bin/mise activate zsh)"'
        create: yes
        state: present

    - name: Copy mise config
      ansible.builtin.copy:
        src: "users/mise.toml"
        dest: "/home/{{ ansible_user_id }}/mise.toml"
