---
roles:
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker.git
    version: 8.0.0
  - name: intellij
    src: https://github.com/gantsign/ansible-role-intellij.git
    version: 7.1.0
  - name: zsh
    src: https://github.com/viasite-ansible/ansible-role-zsh.git
    version: v3.7.10
  - name: vscode
    src: ngetchell.vscode

collections:
  - community.docker
