---
roles:
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker.git
    version: master
  - name: comcast.sdkman
    src: comcast.sdkman
  - name: intellij
    src: https://github.com/gantsign/ansible-role-intellij.git
    version: 6.2.2
  - name: zsh
    src: https://github.com/viasite-ansible/ansible-role-zsh.git
    version: v3.3.2
  - name: nvm
    src: https://github.com/stephdewit/ansible-nvm
    version: v3.3.0

collections:
  - community.docker
