---
roles:
  - name: geerlingguy.docker
    src: https://github.com/geerlingguy/ansible-role-docker.git
    version: master
  - name: comcast.sdkman
    src: comcast.sdkman
  - name: asdf
    src: https://github.com/cimon-io/ansible-role-asdf
  - name: intellij
    src: https://github.com/gantsign/ansible-role-intellij.git
    version: 6.13.0
  - name: zsh
    src: https://github.com/viasite-ansible/ansible-role-zsh.git
    version: v3.5.2
  - name: nvm
    src: https://github.com/stephdewit/ansible-nvm
    version: v3.3.0
  - name: sysctl
    src: robertdebock.sysctl
  - name: hugo
    src: darkwizard242.hugo
  - name: vscode
    src: ngetchell.vscode
  - name: golang
    src: gantsign.golang

collections:
  - community.docker
