---

- name: Install sdkman
  hosts: dev 
  roles:
    - role: comcast.sdkman
      sdkman_user: "{{ ansible_user_id }}"
      sdkman_group: "{{ ansible_user_id }}"
      sdkman_auto_answer: true
      sdkman_update: true
      sdkman_install_packages:
        - { candidate: java, version: 8.0.282-open }
        - { candidate: java, version: 11.0.10-open }
        - { candidate: maven, version: 3.6.3 }
      sdkman_defaults:
        java: 11.0.10-open
  tasks:
    - name: add sdkman in .zshrc.local
      blockinfile:
        path: "/home/{{ ansible_user_id }}/.zshrc.local"
        insertafter: EOF
        block: |
           #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
           export SDKMAN_DIR="/home/{{ ansible_user_id }}/.sdkman"
           [[ -s "/home/{{ ansible_user_id }}/.sdkman/bin/sdkman-init.sh" ]] && source "/home/{{ ansible_user_id }}/.sdkman/bin/sdkman-init.sh"
