---

- name: Install CLI tools
  hosts: dev
  become: yes
  tasks:
    - name: Install apt packages
      ansible.builtin.apt:
        pkg:
          - git
          - curl
          - vim
          - openvpn
          - jq
          - bat
          - ripgrep
          - thefuck
          - yakuake
          - snapd
          - htop

    - name: Add Google Chrome signing key
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/linux_signing_key.pub
        dest: /etc/apt/keyrings/google-chrome.asc
        mode: '0644'
      tags: chrome

    - name: Add Google Chrome repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/google-chrome.asc] https://dl.google.com/linux/chrome/deb/ stable main
        filename: google-chrome
        state: present
      tags: chrome

    - name: Install Google Chrome
      ansible.builtin.apt:
        pkg:
          - google-chrome-stable
      tags: chrome

    - name: Add WezTerm signing key
      ansible.builtin.get_url:
        url: https://apt.fury.io/wez/gpg.key
        dest: /etc/apt/keyrings/wezterm.asc
        mode: '0644'
      tags: wezterm

    - name: Add WezTerm repository
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/etc/apt/keyrings/wezterm.asc] https://apt.fury.io/wez/ * *
        filename: wezterm
        state: present
      tags: wezterm

    - name: Install WezTerm
      ansible.builtin.apt:
        pkg:
          - wezterm
      tags: wezterm
