---

- name: "install {{ ansible_user_id }} config"
  hosts: dev
  tasks:
    - name: copy gitconfig
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/gitconfig"
        dest: "/home/{{ ansible_user_id }}/.gitconfig"
    - name: copy ssh config  
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/config"
        dest: "/home/{{ ansible_user_id }}/.ssh/config"
    - name: copy /etc/hosts
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/hosts"
        dest: "/etc/hosts"
      become: yes
    - name: copy maven settings
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/settings_gitlab_com.xml"
        dest: "/home/{{ ansible_user_id }}/.m2/settings.xml"
    - name: copy ssh key
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "/home/{{ ansible_user_id }}/.ssh/"
        mode: '0600'
      with_fileglob: "users/files/{{ ansible_user_id }}/enovea_rsa*"
    - name: link ssh key
      ansible.builtin.file:
        src: "/home/{{ ansible_user_id }}/.ssh/enovea_rsa"
        dest: "/home/{{ ansible_user_id }}/.ssh/id_rsa"
        state: link
    - name: link ssh key
      ansible.builtin.file:
        src: "/home/{{ ansible_user_id }}/.ssh/enovea_rsa.pub"
        dest: "/home/{{ ansible_user_id }}/.ssh/id_rsa.pub"
        state: link

    - name: copy k9s config
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/k9s/"
        dest: "/home/{{ ansible_user_id }}/.config/k9s/"
      tags: k9s

    - name: copy lazygit config
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/lazygit/"
        dest: "/home/{{ ansible_user_id }}/.config/lazygit/"
      tags: lazygit

    - name: copy glab-cli config
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/glab-cli/"
        dest: "/home/{{ ansible_user_id }}/.config/glab-cli/"
      tags: glab

    - name: copy argocd config
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/argocd/"
        dest: "/home/{{ ansible_user_id }}/.config/argocd/"
      tags: argocd

    - name: copy wezterm config
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/wezterm/"
        dest: "/home/{{ ansible_user_id }}/.config/wezterm/"
      tags: wezterm

    - name: copy docker config
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/docker/config.json"
        dest: "/home/{{ ansible_user_id }}/.docker/config.json"
      tags: docker

    - name: copy p10k config
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/p10k.zsh"
        dest: "/home/{{ ansible_user_id }}/.p10k.zsh"
      tags: zsh

    - name: copy claude settings
      ansible.builtin.copy:
        src: "users/files/{{ ansible_user_id }}/claude/settings.json"
        dest: "/home/{{ ansible_user_id }}/.claude/settings.json"
      tags: claude
