---

- name: Install VSCode
  hosts: dev
  become: yes
  vars: 
  - vscode_extension:
      - senx.warpscript-language
      - vscjava.vscode-maven
      - k--kato.intellij-idea-keybindings
  roles:
    - role: vscode
