---

- name: Install Zsh and plugin etc.
  vars:
    zsh_antigen_bundles_extras:
      - mvn
      - git
      - debian
      - agkozak/zsh-z
      - jump
      - common-aliases
      - git
      - thefuck
      - asdf
  hosts: dev
  roles:
    - role: zsh
      become: yes
  tasks:
    - name: Install fonts powerline
      apt:
        pkg:
          - fonts-powerline
          - fzf
      become: yes
    - name: Ensure the user  has a zsh shell.
      user:
        name: "{{ ansible_user_id }"
        shell: /bin/zsh
        state: present
      become: yes
