---

- name: Install Zsh and plugin etc.
  vars:
    zsh_antigen_bundles_extras:
      - mvn
      - git
      - debian
      - agkozak/zsh-z
      - jump
      - common-aliases
      - git
      - git-flow-completion
      - thefuck
  hosts: dev
  roles:
    - role: zsh
      become: yes
  tasks:
    - name: Install fonts powerline
      apt:
        pkg:
          - fonts-powerline
          - fzf
      become: yes
