[tools]
## dev
java = "openjdk-21"
maven= "3.9.4"
nodejs = "23"
quarkus = "3.14.1"
go = "1.23.2"
aws = "latest"
rust = "latest"
fzf = "latest"
lazygit = "latest"
#git-delta
delta = "latest"

## k8s
kubectl = "latest"
kubectx = "latest"
helm = "latest"
helm-diff = "latest"
helmfile = "latest"
k9s = "latest"
minikube = "latest" # experimental
kind = "latest"

## IA
opencode = "latest"
"npm:ccstatusline" = "latest"
ollama = "latest"
claude-code = "latest"

## ops
argocd = "latest"
httpie-go = "latest"
bitwarden = "latest"
